package com.melikenurozun.recipe_app.data.remote

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import com.melikenurozun.recipe_app.domain.model.Recipe

@Serializable
data class RecipeDto(
    val id: String? = null, // generated by db
    @SerialName("user_id") val userId: String,
    val title: String,
    val ingredients: String,
    val instructions: String,
    @SerialName("image_url") val imageUrl: String? = null,
    val category: String? = null,
    @SerialName("average_rating") val averageRating: Double = 0.0,
    @SerialName("rating_count") val ratingCount: Int = 0,
    @SerialName("created_at") val createdAt: String? = null,
    @SerialName("time_minutes") val timeMinutes: Int = 0
)

fun RecipeDto.toDomain(): Recipe {
    return Recipe(
        id = id ?: "",
        user_id = userId,
        title = title,
        ingredients = ingredients,
        instructions = instructions,
        image_url = imageUrl,
        category = category,
        average_rating = averageRating,
        rating_count = ratingCount,
        created_at = createdAt,
        timeMinutes = timeMinutes
    )
}

fun Recipe.toDto(): RecipeDto {
    return RecipeDto(
        id = if (id.isNotEmpty()) id else null,
        userId = user_id,
        title = title,
        ingredients = ingredients,
        instructions = instructions,
        imageUrl = image_url,
        category = category,
        averageRating = average_rating,
        ratingCount = rating_count,
        createdAt = created_at,
        timeMinutes = timeMinutes
    )
}
